BiblioAsp/Models/Auteur.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BiblioAsp.Models
{
    public class Auteur
    {
        public int Id { get; set; }
        [Required]
        public string Nom { get; set; }
    }
}

BiblioAsp/Controllers/AfficherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiblioAsp.Controllers
{
    public class AfficherController : Controller
    {
        private Models.Interface.IDal dal;
        public AfficherController()
        {
            this.dal = new Models.Dal();
        }
        // GET: Afficher
        public ActionResult Index()
        {
            List<Models.Livre> lesLivres = this.dal.ObtenirLesLivres();
            if (lesLivres.Count == 0)
                return View("../Error");
            return View(lesLivres);
        }
        public ActionResult Livre(int? id)
        {
            List<Models.Livre> listeLivre = this.dal.ObtenirLesLivres((int)id);
            if (listeLivre.Count == 0)
                return View("../Error");
            return View("LivreParId", listeLivre);
        }

        public ActionResult Auteurs(int? id)
        {
            if(!id.HasValue)
            {
                List<Models.Auteur> lesAuteurs = this.dal.ObtenirLesAuteurs();
                return View(lesAuteurs);
            }
            else
            {
                List<Models.Livre> livresByAuteur = this.dal.ObtenirLivresParAuteur((int)id);
                if (livresByAuteur.Count == 0 || livresByAuteur == null)
                    return View("../error");
                else           
                    return View("livreParAuteur",livresByAuteur);
            }       
        }
    }
}

BiblioAsp/Controllers/AjouterController.cs
using BiblioAsp.Models;
using BiblioAsp.Models.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiblioAsp.Controllers
{
    public class AjouterController : Controller
    {
        private IDal dal;

        public AjouterController():this(new Dal())
        {

        }
        public AjouterController(IDal dal)
        {
            this.dal = dal;
        }
        // GET: Livre
        public ActionResult Livre()
        {
            BiblioAsp.ViewModels.AjoutLivreViewModel createLivre = new ViewModels.AjoutLivreViewModel();
            createLivre.Auteurs = this.dal.ObtenirLesAuteurs();
            createLivre.SelectValue = 1;
            return View(createLivre);
        }
        [HttpPost]
        public ActionResult Livre(ViewModels.AjoutLivreViewModel vM)
        {
            vM.Auteurs = this.dal.ObtenirLesAuteurs();
            if(ModelState.IsValid)
            {
                if (!this.dal.LivreExiste(vM.Titre))
                {
                    this.dal.AjouterLivre(vM.Titre, (DateTime)vM.DateParution, vM.SelectValue); // check datetime validation
                    return RedirectToAction("Index", "Home");
                }
                else
                    this.ModelState.AddModelError("Titre", "Le livre est déjà présent dans la base");
            }
            return View(vM);
        }
    }
}

BiblioAsp/Views/Afficher/Auteurs.cshtml
@model List<BiblioAsp.Models.Auteur> 
@{ 
    ViewBag.Title = "Auteurs";
}
<header>
       <h2>Liste des auteurs test</h2>
</header>
    <div>
        @if (Model.Count > 0)
        {
            <table>
                <tr>
                    <th>Nom de l'auteur</th>
                    <th>Livre</th>
                </tr>
                @foreach (BiblioAsp.Models.Auteur a in Model)
                {
                    <tr>
                        <td>@a.Nom</td>
                    </tr>
                }
            </table>
        }
        else
        {
            <p>Aucun auteur n'est présent dans notre base</p>
        }
    </div>

BiblioAsp/Views/Afficher/Index.cshtml
@model List<BiblioAsp.Models.Livre>
@{
    ViewBag.Title = "Nos livres";
}
    <header>
        <h2>Voici le contenu de la biliothèque</h2>
    </header>
    <div>     
      <!-- @if(DateTime.Now.DayOfWeek == DayOfWeek.Friday)
        {
            <text>C'est bientôt le week end !</text>
        }-->
        @section Menu
        {
            <li>@Html.ActionLink("Ajouter un livre", "Livre", "Ajouter")</li> <!-- Section personnalise une partie du layout de base -->
        }
            <table>
                <tr>
                    <th>Titre</th>
                    <th>Date de parution</th>
                    <th>Auteur</th>
                </tr>
            @foreach (BiblioAsp.Models.Livre l in Model)
            {
                <tr>
                    <td>@l.Titre</td>
                    <td>@l.DateParution</td>
                    <td>@l.Auteur.Nom</td>
                </tr>
              } 
            </table>
    </div>

BiblioAsp/Views/Afficher/LivreParAuteur.cshtml
@model List<BiblioAsp.Models.Livre>
@{ 
    ViewBag.Title = "Livre par auteur";
}
        <h2>Les livres disponibles pour @Model[0].Auteur.Nom</h2>
        <div>
                <table>
                    <tr>
                        <th>Titre</th>
                        <th>Date de parution</th>
                    </tr>
                    @foreach (BiblioAsp.Models.Livre l in Model)
                    {
                        <tr>
                            <td>@l.Titre</td>
                            <td>@l.DateParution</td>
                        </tr>
                    }
                </table>
        </div>

BiblioAsp/Views/Afficher/LivreParId.cshtml
@model List<BiblioAsp.Models.Livre>
@{
    ViewBag.Title = "Livre par identifiant";
}
<div> 
        @foreach(BiblioAsp.Models.Livre l in Model)
        {
            <p>Titre : @l.Titre<br/>Date de parution : @l.DateParution</p>
            if(l.Client != null)
            {
                <p>Livre emprunté par Client : @l.Client.Nom<br/>Adresse Email : @l.Client.Email</p>
            }
        }
</div>